<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2025-03-10T15:07:42+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      cache.last_cleared
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '9.3.9',
    'version_db_installed' => '20241115093300',
    'misc' => [
        'login_redirect' => 'HOMEPAGE',
        'access_entity_updated' => 1741158854,
        'latest_version' => '9.3.9',
    ],
    'email' => [
        'default' => [
            'address' => 'kiran.bhatt@resourcifi.com',
        ],
    ],
    'security' => [
        'production' => [
            'mode' => 'development',
        ],
    ],
    'cache' => [
        'last_cleared' => 1741612062,
        'clear' => [
            'thumbnails' => true,
        ],
    ],
    'permissions' => [
        'model' => 'advanced',
    ],
    'seo' => [
        'redirect_to_canonical_url' => false,
        'url_rewriting' => true,
    ],
];
